name: DurabilityAlert
version: 1.6.0
main: io.shantek.DurabilityAlert
api-version: 1.13

commands:
  durabilityalert:
    usage: /<command>
    aliases: [da]
    description: the base durabilityalert command
    permission: shantek.durabilityalert.command
    permission-message: You do not have permission!

permissions:
  shantek.durabilityalert.command:
    description: default durability alert command permission
    default: op
  shantek.durabilityalert.alert:
    description: allows the user to get durability alerts
    default: op