name: DurabilityAlertReloaded
version: '1.6.2'
main: io.shantek.DurabilityAlertContinued
api-version: 1.13

commands:
  durabilityalert:
    usage: /<command>
    aliases: [da]
    description: the base durabilityalert command
    permission: shantek.durabilityalert.use
    permission-message: You do not have permission!

permissions:
  shantek.durabilityalert.use:
    description: allows the user to get durability alerts
    default: op
  shantek.durabilityalert.reload:
    description: ability to reload the plugin
    default: op